[package]
name = "cfdl-parser"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Parser for CFDL - tokens to AST"
publish = false

[dependencies]
thiserror = { workspace = true }

cfdl-lexer = { path = "../cfdl-lexer" }