#!/usr/bin/env python3
"""The documentation surface for machines (docs/32 Phase 2).

Generates, from the same sources the site renders:

  docs/machine/llms.txt               the llms.txt index: normative links plus
                                      the learn.cfdl.dev chapters as Optional
  docs/machine/cfdl-machine-docs.md   the bundle: language spec, grammar (the
                                      real EBNF, not the docs/02 stub),
                                      expression environment, diagnostics
                                      catalog, controlled-English authoring
                                      contract, glossary + terminology
                                      register, pack rosters
  docs/machine/llms-full.txt          the bundle plus every learn chapter,
                                      for consumers that want one document
  docs/machine/diagnostics-repairs.md the repair catalog: per invalid fixture,
                                      the minimal failing example, its golden
                                      diagnostics, and — where one is recorded
                                      under fixtures/repairs/<name>/ — the
                                      minimal fix, compile-verified here

Outputs are committed; `--check` regenerates in memory and byte-compares, so
`make machine-docs-check` is the drift gate (same shape as gen-glossary).
Repairs are compiled in both modes: a repair that stops compiling fails the
gate even when no generated byte changed.

Agents read docs differently: retrieval-sized, deduplicated, versioned. The
bundle carries the normative registers once; the course chapters ride only in
llms-full.txt, because pedagogy restates the spec and must not compete with it
in retrieval.
"""

import json
import os
import pathlib
import re
import subprocess
import sys
import tempfile

sys.stdout.reconfigure(encoding="utf-8")
sys.stderr.reconfigure(encoding="utf-8")

try:
    import tomllib
except ImportError:  # pragma: no cover
    print("python >= 3.11 required (tomllib)", file=sys.stderr)
    sys.exit(2)

ROOT = pathlib.Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "docs" / "machine"
_CLI_NAME = "cfdl.exe" if os.name == "nt" else "cfdl"
CFDL = os.environ.get("CFDL_BIN", str(ROOT / "target" / "debug" / _CLI_NAME))

SITE = "https://cfdl.dev"
LEARN = "https://learn.cfdl.dev"

# Every generated file opens with this line so a reader (human or agent) knows
# where the bytes come from and how to refresh them.
def provenance(kind: str) -> str:
    return (
        f"<!-- GENERATED {kind} by tools/gen-machine-docs.py — do not edit by hand. "
        f"Regenerate: make machine-docs -->"
    )


def workspace_version() -> str:
    manifest = tomllib.loads((ROOT / "Cargo.toml").read_text(encoding="utf-8"))
    return manifest["workspace"]["package"]["version"]


def read(path: pathlib.Path) -> str:
    return path.read_text(encoding="utf-8")


# --- The diagnostics register (docs/08 §7) ----------------------------------

BULLET = re.compile(r"^-\s+`([EWI]\d+_[A-Z0-9_]+)`\s*(?:—\s*(.*))?$")


def documented_codes() -> dict[str, str]:
    """Code -> first sentence, from the §7 bullet register."""
    codes: dict[str, str] = {}
    in_register = False
    for line in read(ROOT / "docs" / "08_diagnostics.md").splitlines():
        if line.startswith("## 7"):
            in_register = True
        elif line.startswith("## ") and in_register:
            break
        if not in_register:
            continue
        match = BULLET.match(line)
        if match:
            codes[match.group(1)] = (match.group(2) or "").strip()
    return codes


# --- The repair catalog ------------------------------------------------------

def fixture_cases() -> list[dict]:
    """One entry per invalid fixture: sources, golden diagnostics, repair."""
    cases = []
    for fixture in sorted((ROOT / "fixtures" / "invalid").iterdir()):
        if not fixture.is_dir():
            continue
        golden = ROOT / "gold" / "diag" / f"{fixture.name}.diag.json"
        diags = json.loads(read(golden)) if golden.exists() else []
        sources = {
            p.name: read(p) for p in sorted(fixture.glob("*.cfdl"))
        }
        repair_dir = ROOT / "fixtures" / "repairs" / fixture.name
        repair = {
            p.name: read(p) for p in sorted(repair_dir.glob("*.cfdl"))
        } or None
        cases.append(
            {
                "name": fixture.name,
                "sources": sources,
                "diags": diags,
                "repair": repair,
            }
        )
    return cases


def check_repairs_compile(cases: list[dict]) -> None:
    """Every recorded repair must compile; a repair with no fixture is an error.

    A repair is the catalog's claim that the fix is minimal AND valid — an
    uncompiled fix is a guess, which is exactly what this catalog exists to
    replace.
    """
    fixture_names = {case["name"] for case in cases}
    for stray in sorted((ROOT / "fixtures" / "repairs").glob("*/")):
        if stray.name not in fixture_names:
            raise SystemExit(
                f"fixtures/repairs/{stray.name} has no fixtures/invalid/{stray.name}"
            )
    if not pathlib.Path(CFDL).exists():
        raise SystemExit(f"cfdl binary not found at {CFDL}; run `cargo build -p cfdl-cli`")
    for case in cases:
        if case["repair"] is None:
            continue
        with tempfile.TemporaryDirectory() as tmp:
            model_dir = pathlib.Path(tmp) / case["name"]
            model_dir.mkdir()
            for name, source in case["repair"].items():
                (model_dir / name).write_text(source, encoding="utf-8")
            out = pathlib.Path(tmp) / "ir.json"
            result = subprocess.run(
                [CFDL, "compile", str(model_dir), "--out", str(out), "--packs", str(ROOT / "packs")],
                capture_output=True,
                encoding="utf-8",
            )
            if result.returncode != 0:
                raise SystemExit(
                    f"fixtures/repairs/{case['name']}/model.cfdl does not compile:\n"
                    f"{result.stderr.strip()}"
                )


def render_repairs(cases: list[dict], registered: dict[str, str]) -> str:
    exemplified = sorted({d["code"] for case in cases for d in case["diags"]})
    repaired = [case for case in cases if case["repair"] is not None]
    unexemplified = sorted(set(registered) - set(exemplified))
    unregistered = sorted(set(exemplified) - set(registered))

    lines = [
        provenance("diagnostics -> repair catalog"),
        "",
        "# CFDL diagnostics — repair catalog",
        "",
        f"CFDL {workspace_version()}. For each diagnostic code with a minimal failing",
        "example (`fixtures/invalid/`), this catalog shows the example, the exact",
        "diagnostics it produces (`gold/diag/`, byte-asserted in CI), and — where one",
        "is recorded — the minimal compile-verified fix (`fixtures/repairs/`).",
        "",
        "Diagnostics are the repair signal: read the `code`, `message`, `span`, and",
        "`hint`, change the model, recompile. The catalog is how an agent learns what",
        "each code looks like in the flesh before it meets one.",
        "",
        f"**Coverage:** {len(registered)} codes in the docs/08 §7 register; "
        f"{len(exemplified)} exemplified here; {len(repaired)} of "
        f"{len(cases)} examples carry a recorded fix.",
        "",
    ]
    if unregistered:
        lines += [
            "Exemplified but missing from the docs/08 register (drift to fix): "
            + ", ".join(f"`{code}`" for code in unregistered),
            "",
        ]
    for case in cases:
        codes = ", ".join(sorted({d["code"] for d in case["diags"]})) or "(no golden)"
        lines += [f"## {case['name']} — {codes}", ""]
        for name, source in case["sources"].items():
            label = "" if name == "model.cfdl" else f" — {name}"
            lines += [f"Failing example{label}:", "", "```cfdl", source.rstrip(), "```", ""]
        for diag in case["diags"]:
            lines.append(f"- `{diag['code']}` ({diag['severity']}): {diag['message']}")
            if diag.get("hint"):
                lines.append(f"  - hint: {diag['hint']}")
        lines.append("")
        if case["repair"] is not None:
            for name, source in case["repair"].items():
                label = "" if name == "model.cfdl" else f" — {name}"
                lines += [
                    f"Minimal fix (compiles){label}:",
                    "",
                    "```cfdl",
                    source.rstrip(),
                    "```",
                    "",
                ]
        else:
            lines += ["Fix: not yet recorded.", ""]
    if unexemplified:
        lines += [
            "## Registered codes with no example yet",
            "",
            "Documented in docs/08 §7, awaiting a minimal failing fixture:",
            "",
        ]
        lines += [f"- `{code}` — {registered[code]}" for code in unexemplified]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# --- Pack rosters ------------------------------------------------------------

def pack_rosters() -> str:
    lines = []
    for pack_dir in sorted((ROOT / "packs").iterdir()):
        manifest_path = pack_dir / "pack.toml"
        if not manifest_path.exists() or pack_dir.name == "testpack":
            continue
        manifest = tomllib.loads(read(manifest_path))
        pack = manifest.get("pack", manifest)
        name = pack.get("name", pack_dir.name)
        lines += [
            f"### Pack `{name}` {pack.get('version', '')}".rstrip(),
            "",
        ]
        if pack.get("description"):
            lines += [pack["description"], ""]
        if pack.get("cadences"):
            lines += ["Cadences: " + ", ".join(pack["cadences"]), ""]
        types_path = pack_dir / "ontology" / "types.toml"
        if types_path.exists():
            ontology = tomllib.loads(read(types_path))
            contracts = ontology.get("contracts", [])
            if contracts:
                lines += [
                    "Contract types (a `contract <name>` declaration lowers to streams "
                    "through the pack's rule for it; a type with no rule name is an "
                    "election the engine resolves):",
                    "",
                    "| type | contract name | parties | description |",
                    "|---|---|---|---|",
                ]
                for contract in contracts:
                    lines.append(
                        "| `{}` | {} | {} | {} |".format(
                            contract.get("type_id", ""),
                            f"`{contract['contract_name']}`"
                            if contract.get("contract_name")
                            else "(election)",
                            ", ".join(contract.get("parties", [])),
                            (contract.get("description") or "").replace("|", "\\|"),
                        )
                    )
                lines.append("")
        metrics_path = pack_dir / "metrics.toml"
        if metrics_path.exists():
            specs = tomllib.loads(read(metrics_path)).get("metrics", [])
            ids = [spec["id"] for spec in specs if "id" in spec]
            if ids:
                lines += ["Metrics: " + ", ".join(f"`{i}`" for i in ids), ""]
        templates_path = pack_dir / "templates.toml"
        if templates_path.exists():
            templates = tomllib.loads(read(templates_path)).get("templates", [])
            if templates:
                lines += [
                    "Templates (starting points; the `skeleton` MCP tool assembles them "
                    "into a compiling model):",
                    "",
                ]
                lines += [
                    "- `{}` — {}".format(t["id"], t.get("label", ""))
                    for t in templates
                ]
                lines.append("")
    return "\n".join(lines).rstrip() + "\n"


# --- The bundle --------------------------------------------------------------

def section(title: str, body: str, note: str | None = None) -> str:
    parts = [f"\n\n---\n\n# {title}\n"]
    if note:
        parts.append(f"\n_{note}_\n")
    parts.append("\n" + body.strip() + "\n")
    return "".join(parts)


def render_bundle() -> str:
    version = workspace_version()
    head = "\n".join(
        [
            provenance("machine docs bundle"),
            "",
            f"# CFDL machine documentation bundle — v{version}",
            "",
            "> CFDL (Cash Flow Domain Language) is a declarative language for financial",
            "> cash-flow models with a deterministic compile -> run cycle, structured",
            "> diagnostics, and an externally-benchmarked engine. Contracts lower to",
            "> streams: a `contract` declaration is vocabulary that a pack's lowering",
            "> rule turns into streams; streams are the cash. Streams evaluate first on",
            "> their schedules, then logic and events act on those amounts, then",
            "> financing and distributions run over the aggregated flows.",
            "",
            "One document, generated from the normative sources the site renders.",
            "Deduplicated: the course at learn.cfdl.dev restates this material",
            "pedagogically and is deliberately not here (see llms-full.txt).",
        ]
    )
    body = head
    body += section("Language specification", read(ROOT / "docs" / "01_language_spec.md"))
    body += section(
        "Grammar (EBNF)",
        "```ebnf\n" + read(ROOT / "docs" / "schemas" / "CFDL_v0_1_Grammar.ebnf").strip() + "\n```",
        note="The complete grammar. docs/02_grammar.md on the site is a pointer to this file.",
    )
    body += section(
        "Expression environment", read(ROOT / "docs" / "03_expression_environment.md")
    )
    body += section(
        "IR schema",
        read(ROOT / "docs" / "05_ir_schema.md"),
        note="Generated from docs/schemas/ir.schema.json; the JSON Schema itself is "
        "served at /schemas/CFDL_v0_1_IR.schema.json.",
    )
    body += section(
        "Results schema",
        read(ROOT / "docs" / "06_results_schema.md"),
        note="Generated from docs/schemas/results.schema.json; the JSON Schema itself "
        "is served at /schemas/CFDL_v0_1_Results.schema.json.",
    )
    body += section("Pack interface", read(ROOT / "docs" / "07_pack_interface.md"))
    body += section("Diagnostics", read(ROOT / "docs" / "08_diagnostics.md"))
    body += section(
        "Controlled English — the authoring contract",
        read(ROOT / "docs" / "22_cfdl_controlled_english.md"),
        note="The register an authoring agent should emit. The mechanical subset is "
        "enforced by tools/check-site-voice.py; the terminology below is the word list.",
    )
    body += section("Glossary", read(ROOT / "docs" / "glossary.md"))
    body += section(
        "Terminology register",
        "```toml\n" + read(ROOT / "docs" / "terminology.toml").strip() + "\n```",
    )
    body += section(
        "Pack rosters",
        pack_rosters(),
        note="Generated from packs/*/ (pack.toml, ontology/types.toml, metrics.toml, "
        "templates.toml). The diagnostics -> repair catalog is a sibling document: "
        "diagnostics-repairs.md.",
    )
    return body.strip() + "\n"


# --- The valid corpus --------------------------------------------------------

def render_valid_examples() -> str:
    lines = [
        provenance("valid examples corpus"),
        "",
        "# CFDL valid examples — the golden corpus",
        "",
        f"CFDL {workspace_version()}. Every model below compiles, and its IR and",
        "results are byte-asserted against goldens in CI (`fixtures/valid/`,",
        "`gold/ir/`, `gold/results/`). Each is single-purpose: the directory name",
        "says what it exercises. This is what right looks like — positive few-shot",
        "material to pair with the diagnostics repair catalog.",
        "",
    ]
    count = 0
    for fixture in sorted((ROOT / "fixtures" / "valid").iterdir()):
        if not fixture.is_dir():
            continue
        sources = sorted(fixture.glob("*.cfdl"))
        if not sources:
            continue
        count += 1
        lines += [f"## {fixture.name}", ""]
        for source in sources:
            if source.name != "model.cfdl":
                lines += [f"`{source.name}`:", ""]
            lines += ["```cfdl", read(source).rstrip(), "```", ""]
    lines.insert(6, f"{count} models.")
    lines.insert(7, "")
    return "\n".join(lines).rstrip() + "\n"


# --- learn chapters ----------------------------------------------------------

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.DOTALL)


def learn_chapters() -> list[dict]:
    chapters = []
    for path in sorted((ROOT / "learn" / "content" / "chapters").glob("*.mdx")):
        raw = read(path)
        match = FRONTMATTER.match(raw)
        meta: dict[str, str] = {}
        body = raw
        if match:
            body = raw[match.end() :]
            for line in match.group(1).splitlines():
                if ":" in line:
                    key, _, value = line.partition(":")
                    meta[key.strip()] = value.strip().strip('"')
        # Chapter URLs drop the file's number prefix: 01-why-a-language.mdx
        # is served at /chapters/why-a-language.
        slug = re.sub(r"^\d+-", "", path.stem)
        chapters.append(
            {
                "slug": slug,
                "title": meta.get("title", slug),
                "description": meta.get("description", ""),
                "body": body.strip(),
            }
        )
    return chapters


# --- llms.txt ----------------------------------------------------------------

def render_llms_txt(chapters: list[dict]) -> str:
    version = workspace_version()
    lines = [
        "# CFDL",
        "",
        "> CFDL (Cash Flow Domain Language) is a declarative, source-available language",
        "> for financial cash-flow models: a deterministic compile -> run cycle,",
        "> structured diagnostics, domain packs, and an engine graded against external",
        "> reference benchmarks. Contracts lower to streams — a contract declaration is",
        "> vocabulary a pack's lowering rule turns into streams, and streams are the",
        "> cash.",
        "",
        f"Version {version}. Machine artifacts on this site are generated from the",
        "repository's normative sources under CI; if this file and a doc page ever",
        "disagree, the repository is the source of truth.",
        "",
        "## Machine bundle",
        "",
        f"- [Machine docs bundle]({SITE}/machine/cfdl-machine-docs.md): the language",
        "  spec, full EBNF grammar, expression environment, IR and results schemas,",
        "  pack interface, diagnostics catalog, controlled-English authoring contract,",
        "  glossary, terminology register, and pack rosters, in one versioned document",
        f"- [Diagnostics repair catalog]({SITE}/machine/diagnostics-repairs.md): per",
        "  diagnostic code, a minimal failing example and (where recorded) its minimal",
        "  compile-verified fix",
        f"- [Valid examples corpus]({SITE}/machine/valid-examples.md): every golden",
        "  fixture model — single-purpose, compiling, byte-asserted in CI; what right",
        "  looks like",
        f"- [llms-full.txt]({SITE}/llms-full.txt): the bundle plus every course",
        "  chapter, for consumers that want a single document",
        "",
        "## Specification",
        "",
        f"- [Language specification]({SITE}/docs/specification/language-spec)",
        f"- [Grammar]({SITE}/docs/specification/grammar) — full EBNF at",
        f"  [{SITE}/schemas/CFDL_v0_1_Grammar.ebnf]({SITE}/schemas/CFDL_v0_1_Grammar.ebnf)",
        f"- [Expression environment]({SITE}/docs/specification/expression-environment)",
        f"- [Diagnostics]({SITE}/docs/specification/diagnostics)",
        f"- [IR schema]({SITE}/docs/specification/ir-schema) — JSON Schema at",
        f"  [{SITE}/schemas/CFDL_v0_1_IR.schema.json]({SITE}/schemas/CFDL_v0_1_IR.schema.json)",
        f"- [Results schema]({SITE}/docs/specification/results-schema) — JSON Schema at",
        f"  [{SITE}/schemas/CFDL_v0_1_Results.schema.json]({SITE}/schemas/CFDL_v0_1_Results.schema.json)",
        f"- [Pack interface]({SITE}/docs/specification/pack-interface)",
        f"- [Glossary]({SITE}/docs/glossary)",
        "",
        "## Optional",
        "",
        "The CFDL course — pedagogical, restates the specification narratively:",
        "",
    ]
    for chapter in chapters:
        desc = f": {chapter['description']}" if chapter["description"] else ""
        lines.append(f"- [{chapter['title']}]({LEARN}/chapters/{chapter['slug']}){desc}")
    return "\n".join(lines).rstrip() + "\n"


def render_llms_full(bundle: str, chapters: list[dict]) -> str:
    parts = [
        provenance("llms-full.txt"),
        "",
        bundle.split("\n", 1)[1].strip(),  # bundle minus its own provenance line
        "",
        "\n\n---\n\n# Valid examples — the golden corpus\n",
        "\n" + render_valid_examples().split("\n", 2)[2].strip() + "\n",
        "\n\n---\n\n# The CFDL course (learn.cfdl.dev)\n",
        "\nPedagogical: the chapters restate the specification narratively. The",
        "specification above is normative where they differ.\n",
    ]
    for chapter in chapters:
        parts.append(f"\n\n## {chapter['title']}\n")
        if chapter["description"]:
            parts.append(f"\n_{chapter['description']}_\n")
        parts.append("\n" + chapter["body"] + "\n")
    return "\n".join(p.strip("\n") for p in parts if p.strip("\n")) \
        .replace("\n\n\n", "\n\n") + "\n"


# --- main --------------------------------------------------------------------

def outputs() -> dict[str, str]:
    registered = documented_codes()
    cases = fixture_cases()
    check_repairs_compile(cases)
    bundle = render_bundle()
    chapters = learn_chapters()
    return {
        "cfdl-machine-docs.md": bundle,
        "diagnostics-repairs.md": render_repairs(cases, registered),
        "valid-examples.md": render_valid_examples(),
        "llms.txt": render_llms_txt(chapters),
        "llms-full.txt": render_llms_full(bundle, chapters),
    }


def main() -> int:
    check = "--check" in sys.argv[1:]
    generated = outputs()
    if check:
        stale = []
        for name, content in generated.items():
            target = OUT_DIR / name
            if not target.exists() or read(target) != content:
                stale.append(name)
        if stale:
            print(
                "machine docs are out of date with their sources:\n"
                + "".join(f"  docs/machine/{name}\n" for name in stale)
                + "\n  Regenerate them:  make machine-docs",
                file=sys.stderr,
            )
            return 1
        print(f"machine-docs: OK ({len(generated)} artifacts current)")
        return 0
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for name, content in generated.items():
        (OUT_DIR / name).write_text(content, encoding="utf-8")
        print(f"wrote docs/machine/{name} ({len(content.encode('utf-8')):,} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
